### ISSUE TITLE
FR: sort plugins by name not (presumably) URI

### ISSUE THREAD

**Issue by SpotlightKid** [brummer10/jalv_select#10]
Sorting by URI makes no sense IMHO, if the URI isn't shown in the GUI.

**Comment by brummer10** [comment]
It isn't sorted at all (by jalv.select), it is the world as given by lilv.

**Comment by SpotlightKid** [comment]
It should be, IMHO :)

**Comment by brummer10** [comment]
Okay, make sense. Done.

**Comment by trebmuh** [comment]
Sweat ! That's a greatly useful little improvement. Thanks for that to you both.

**Comment by SpotlightKid** [comment]
I get some strange sorting here. Maybe it's because of the asterisk in the name of the Caps plug-ins? Probably a GTK issue and only a minor error, but I thought I'd let you know.

![bildschirmfoto_2016-03-25_12-14-39](https://cloud.githubusercontent.com/assets/5719151/14043324/4454cf44-f283-11e5-8371-9d592203079f.png)

**Comment by brummer10** [comment]
Yes, thanks, that's indeed a GTK issue,
