### ISSUE TITLE
systray icon

### ISSUE THREAD

**Issue by trebmuh** [brummer10/jalv_select#11]
Hi @brummer10 , I can't figure out why but the systray icon doesn't appear on my installation (last git commit). When launching jalv.select I only have on small black line (on the left of the speaker icon):
![capture](https://cloud.githubusercontent.com/assets/8705846/13988456/5aaa4cc4-f10c-11e5-826c-42b90a283c92.png).
For information, I'm running MATE 1.8 on a Debian Jessie and I've got lv2.png installed in /usr/share/pixmaps/ .
Any idea ?

**Comment by brummer10** [comment]
Hi 
This seems to be a bug in MATE, a couple of reports pops up in the NET. 
However, I'm running debian/sid, so I've installed MATE as well, and found it is a issue related to the icon size. Re-sized the icon from 32x32 to 24x24px fixed it here.

Let me know if I could close this bug report?

regards
hermann

**Comment by trebmuh** [comment]
Unfortunately, it didn't change anything here :/

I've been looking around today, with a bunch of trial/error and I might have find something: if I change the line n°273 in jalv.select.cpp from: `status_icon(Gtk::StatusIcon::create_from_file("lv2.png")),` to `status_icon(Gtk::StatusIcon::create_from_file("/usr/share/pixmaps/lv2.png")),` (which is the place the icon is going to on my Debian Jessie system) and I rebuilt it, then I've got the systray icon working properly.

Does that helps you to understand something?

**Comment by brummer10** [comment]
Okay, then this was only the half way. 
The makefile will now create a config.h file to define the PIXMAPS_PATH so that jalv.select will find the image, regardless were you install it.

**Comment by trebmuh** [comment]
Sweat, I've built from the 0.6 tagged version, and it does work as expected. Thanks.

By the way, thanks for the systray icon feature, it's really handy to have access to jalv.select quickly and it doesn't look to be using too much resource (0% of CPU and 34M of RAM here).

I'm closing this issue.
