### ISSUE TITLE
Makefile doesn't support parallel builds

### ISSUE THREAD

**Issue by SpotlightKid** [brummer10/jalv_select#12]
My package build system (`makepkg` on Arch) uses parallel builds by default, so I sometimes got this error when building jalv.select via a `PKGBUILD`:

```
make: *** Keine Regel vorhanden, um das Ziel „config.h“, 
  benötigt von „jalv.select“, zu erstellen.  Schluss.
make: *** Es wird auf noch nicht beendete Prozesse gewartet...
```

Seems like a race condition for the creation of / check for `config.h`.

I can workaround this by using `make -j 1` explicitly as the build command in the `PKGBUILD`, but I think this restriction should be mentioned in the README (or fixed).

**Comment by brummer10** [comment]
By default make usually runs with -j 1, it seems arch have set this value different. 
However, I found a way to set the targets accordingly to allow multiple jobs settings (even when the build will run serial, as it isn't more then one generated header file and one source file). Let me know if it solve your issue, or just close this bug when done.

regards
hermann

**Comment by SpotlightKid** [comment]
It seems to be fixed. Hard to tell for sure, since it triggered only occasionally. Closing this issue anyway.
