### ISSUE TITLE
Commit 00b98f9 breaks scrolling the list via keyboard

### ISSUE THREAD

**Issue by SpotlightKid** [brummer10/jalv_select#13]
When you use PageUp/Down or Up/Down keys to scroll the list, it only scrolls one position/page, then stops, because the preset selection menu pops up, which takes the keyboard focus.

**Comment by SpotlightKid** [comment]
Or maybe it was broken before already.

**Comment by brummer10** [comment]
Well, that was broken before. I've enabled it now, but, you must set the focus on the scrollbar on the right side, (click on it) to make it work.

**Comment by SpotlightKid** [comment]
That fix at least makes it possible to use the keyboard to scroll the list, but having to use the mouse first, is a bit unsatisfactory.

I tried to set the focus on the scrollbar via TAB, which works in principle, but if I then use the Up/Down keys, the focus goes to the search field instead. PageUp/Down keys work fine.

Ideally I would like to scroll to and select a plugin and then the preset just using the keyboard, which currently doesn't seem possible.

**Comment by brummer10** [comment]
Hi
I've enabled now to scroll and select a plug/preset by keyboard. No mouse needed any more.
Hope that fix this bug.

regards
hermann

**Comment by trebmuh** [comment]
Tested and it's working. Thanks.

**Comment by brummer10** [comment]
That's good to know. 
I've added some more keyboard shortcuts in the meantime.
Now, you could press escape to minimize to systray icon,
delete to disable the preset menu
alt+q to quit
alt+r to refresh the list.

**Comment by trebmuh** [comment]
Sweat. Confirming that it is working. Thanks.

**Comment by SpotlightKid** [comment]
Yes, I can confirm it too. The keyboard shortcuts are very helpful, but I think it would be better to adhere better to common standards. Particularly I would change:

`Alt-q` to `Ctrl-q`
`Alt-r` to `Ctrl-r` and/or `F5`
`Escape` for minimize to `Ctrl-w` (i.e. "Close window" but don't quit)
`Delete` for close preset menu to `Escape`.

Also I would expect `Space` to activate a plugin menu entry (in addition to `Enter`).

**Comment by brummer10** [comment]
> Yes, I can confirm it too. The keyboard shortcuts are very helpful, but I think it would be better to adhere better to common standards. Particularly I would change:
> 
> Alt-q to Ctrl-q
> Alt-r to Ctrl-r and/or F5
> Escape for minimize to Ctrl-w (i.e. "Close window" but don't quit)
> Delete for close preset menu to Escape.
> 
> Also I would expect Space to activate a plugin menu entry (in addition to Enter).

Alt be the default modifier for buttons, Ctrl is the default for menus.
However, I've added the Ctrl modifier so that both work now.
I've replaced Escape with Ctrl-w for minimize the window to systray, and additional I've added a Global HotKey (SHIFT+ESCAPE) to show/hide jalv.select from the systray icon.
Also Space works now to activate a plugin.

I guess now, jalv.select could be completely keyboard driven.

**Comment by SpotlightKid** [comment]
Excellent!

Concerning Alt vs. Ctrl: GTK has this concept of actions, which can be bound to different triggers like menus, buttons and keyboard shortcuts.

The Shift+Escape combination doesn't work for me, probably it's shadowed by my window manager. There are some other ideas that are related to this, so I'll discuss this elsewhere.
