### ISSUE TITLE
[feature request] start hided (as a systray icon)

### ISSUE THREAD

**Issue by trebmuh** [brummer10/jalv_select#14]
Hi brummer,
I've placed jalv.select into my "applications at start" on my desktop environment (MATE). Then, when connecting to my desktop session, it launches jalv.select automatically. Since jalv.select now features the "systray icon" functionality, would that be possible to add an option (a tick box) which would launches jalv.select _only_ in the systray ?

**Comment by brummer10** [comment]
Hi
I've added a command line option (-s) to start minimized in systray. 
Hope that will do it for you.

**Comment by trebmuh** [comment]
Awesome. Yes it does work for me (and I guess you do not want to start adding an option tab in the GUI now) so it's fine. Thank you.
