### ISSUE TITLE
FR: option to set initial window height or remember it

### ISSUE THREAD

**Issue by SpotlightKid** [brummer10/jalv_select#16]
When jalv.select is started its window has a rather small height, so that only 4 plugin entries are shown on my system.

I would like a way to set the initial window height (in rows or pixels) or size, e.g. via a command line option, or for jalv.select to remember it's last windows size somehow.

**Comment by brummer10** [comment]
Done.
Added a new option -H (--high) to set the initial window high in pixel.

**Comment by SpotlightKid** [comment]
Very much appreciated.
