### ISSUE TITLE
FR: add a way to copy plugin URI of selected plugin to clipboard

### ISSUE THREAD

**Issue by SpotlightKid** [brummer10/jalv_select#17]
For example with  Control-C or with middle or right mouse click.

Would be useful, if you want to start a plugin with jalv in script after using jalv-select to find and try out candidates.

**Comment by brummer10** [comment]
Okay, done, you could copy the URI with right mouse click to clipboard now.

**Comment by SpotlightKid** [comment]
Sweet!

Though I would always like to able to control jalv.select completely by keyboard, so I added Control-C as a shortcut (#18).

I also don't like the space being prepended to the URI. I guess that's for convenience when pasting it to a command line, but I think it's annoying when you want to paste the URI somewhere else, e.g. in a Markdown document. I put in a commit to remove that in the PR too, but feel free to cherry-pick and leave it out.

**Comment by brummer10** [comment]
Thanks Chris, I've merged your patch. 
Well, I put the space before the URI, as I think it could be useful, but you are right, for correctness and workflow it may be better without it.
