### ISSUE TITLE
FR: search plugin URI as well

### ISSUE THREAD

**Issue by SpotlightKid** [brummer10/jalv_select#20]
When I type "tuna" into the search box I get no results, even if I have x42's [tuna](http://x42-plugins.com/x42/x42-tuner) plugin installed, because the actual plugin name set in it's TTL file is "Instrument Tuner", not "Tuna". But the plugin URI contains the substring "tuna", so if jalv-select where to search the plugin URIs as well, I would be able to find plugins easier.

**Comment by brummer10** [comment]
Okay, I've added the plugin uri to the search path.

**Comment by SpotlightKid** [comment]
Very nice. Thank you!

**Comment by brummer10** [comment]
I just notice a little issue in the tool-tip display now, I've fixed that with the latest commit.

**Comment by trebmuh** [comment]
nice addition !

**Comment by trebmuh** [comment]
Packaged in LibraZiK now.
