### ISSUE TITLE
favorite plugins list

### ISSUE THREAD

**Issue by trebmuh** [brummer10/jalv_select#22]
When you have a lot of plugins installed (jalv.select here reports 637 plugins), it can be a bit boring (from an user point of view) to scroll to the ones you're using frequently.

What about a list of the "favorite ones" you could select from the main list?

We could have a case "favorite" to tick on each plugin-line on the main list, and a button to push to switch between the main list and the favorite one (ie: automatically filled with the plugins where the "favorite" case is ticked)?

**Comment by SpotlightKid** [comment]
I kinda like the idea.

And/Or put the favorite icon in it's own column, then make the columns sortable by clicking on the column header. The filter button could be next to the search entry field.

**Comment by brummer10** [comment]
Hi

Yes, it's a real good idea. I've added a toggle column to select the favourites and a switch to select between the view. The favourite list will be stored in 
home/user/.config/jalv.select.conf 

regards
hermann

**Comment by SpotlightKid** [comment]
Nice!

On minor correction: in English it's either "favorite" (AE) or "favourite" (BE), not "favorit".

**Comment by brummer10** [comment]
Oh, thanks, yea my linguistic isn't that nice formed. Fixed now.

**Comment by trebmuh** [comment]
Glad you found this suggestion interesting. Awesome you worked towards it that fast. Thanks @brummer10 !
