### ISSUE TITLE
Makefile mistakes

### ISSUE THREAD

**Issue by yurivict** [brummer10/jalv_select#24]
The following items should have ```+=```, not just ```=```:
* PREFIX
* CXXFLAGS
* LDFLAGS

This will allow the user to set the flags from outside.

**Comment by brummer10** [comment]
You didn't need to declare vars with `+=` to allow to overwrite them. The user input will overwrite them even if you just declare them with` =`

regards
hermann

**Comment by yurivict** [comment]
I am sorry, I meant ```?=```. They should be declared with ```?=```, without this user input will not override them.

**Comment by brummer10** [comment]
Which maketools do you use? Do you have trouble overwriting the vars?
As I said above, usually user input will overwrite the vars, there is no need for declare them with `?=`
See here:
https://www.gnu.org/software/make/manual/html_node/Overriding.html

**Comment by yurivict** [comment]
> Which maketools do you use? Do you have trouble overwriting the vars?

gmake through the FreeBSD ports framework.

When the variable is defined with ```=``` , setting it in the command line indeed overrides it, but setting it in the environment doesn't.

When the variable is defined with ```?=``` , setting it both in the command line and in the environment set it. So it depends on the way toolchain works, and ```?=``` is more generic.

**Comment by brummer10** [comment]
Okay, good point. 
I've committed a fix now.

regards
hermann

**Comment by yurivict** [comment]
Thanks!
