### ISSUE TITLE
[FEATURE REQUEST] showing the number and type of inputs/outputs

### ISSUE THREAD

**Issue by trebmuh** [brummer10/jalv_select#25]
I don't know if that easily doable but I'd love to have that in jalv.select.

Scenario case is: I've got > 600 LV2 plugins and I'm looking (let's say) for a reverb. I've got 28 possibilities (thanks to the FLOSS devs!):
![jalv select](https://user-images.githubusercontent.com/8705846/34543661-5ae52a60-f0e2-11e7-8e94-73409dbc34ac.png)

It'd be great if we can have a column (or an info when mouse-overing the line maybe?) where we could find the number of:
- audio input (usual case: mono or stereo)
- audio output (same)
- same for MIDI input/output
- a "misc" section (which could be a sidechain input as an example, if that's easily findable by jalv.select)

At least, knowing quickly if the effect I'm feeling that I'd like to try is mono or stereo audio inputs, and the same for the output would be already something speeding up the workflow (it's time consuming to load one, wait for the GUI to appear, go to qjackctl/cadence/... to check if it's a mono or a stereo one, close it because "I was searching for a stereo one and it's mono", then try again with another).

Happy new year to you and yours and thanks for your wonderful software (jalv.select, gx-plugins, guitarix,...).

**Comment by brummer10** [comment]
For now I've added Audio in/output ports to the tooltip text of the plugs.

regards
hermann

**Comment by trebmuh** [comment]
Awesome. It is really nice. Thanks @brummer10 .

_PS: BTW compiling it, I [had this issue too](https://github.com/brummer10/jalv_select/issues/26#issuecomment-357542575)_

**Comment by brummer10** [comment]
Now it will show midi in/output ports as well in the tooltip text. 

I'm unsure how to proceed with issue #26  
I'm using debian/sid  and has no issues with build.

regards
hermann

**Comment by trebmuh** [comment]
Awesome. Thanks again @brummer10 !

_(PS: all good for https://github.com/brummer10/jalv_select/issues/26 , thanks.)_
