### ISSUE TITLE
issues building on Arch64

### ISSUE THREAD

**Issue by funkmuscle** [brummer10/jalv_select#3]
Hermann, tried to run jalv.select today and it wouldn't launch.. decided to to clean out and do a fresh pull. it now would not build.

/usr/include/gtkmm-2.4/gtkmm/treeview.h:2289:5:   required from here
/usr/include/sigc++-2.0/sigc++/functors/slot.h:172:72: error: ‘operator()’ not defined
       return (typed_rep->functor_).SIGC_WORKAROUND_OPERATOR_PARENTHESES<type_trait
                                                                        ^
In file included from /usr/include/glibmm-2.4/glibmm/containerhandle_shared.h:23:0,
                 from /usr/include/glibmm-2.4/glibmm/arrayhandle.h:23,
                 from /usr/include/glibmm-2.4/glibmm.h:91,
                 from /usr/include/gtkmm-2.4/gtkmm.h:87,
                 from jalv.select.cpp:1:
/usr/include/glibmm-2.4/glibmm/refptr.h: At global scope:
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Glib::Binding]’ used but never defined
   inline ~RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:107:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr(const Glib::RefPtr<T_CppObject>&) [with T_CppObject = Glib::Binding]’ used but never defined
   inline RefPtr(const RefPtr& src) noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:101:19: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr(T_CppObject_) [with T_CppObject = Glib::ByteArray]’ used but never defined
   explicit inline RefPtr(T_CppObject_ pCppObject) noexcept;
                   ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Glib::ByteArray]’ used but never defined
   inline ~RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:107:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr(const Glib::RefPtr<T_CppObject>&) [with T_CppObject = Glib::ByteArray]’ used but never defined
   inline RefPtr(const RefPtr& src) noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Gio::Mount]’ used but never defined
   inline ~RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:107:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr(const Glib::RefPtr<T_CppObject>&) [with T_CppObject = Gio::Mount]’ used but never defined
   inline RefPtr(const RefPtr& src) noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Gio::Drive]’ used but never defined
   inline ~RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:107:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr(const Glib::RefPtr<T_CppObject>&) [with T_CppObject = Gio::Drive]’ used but never defined
   inline RefPtr(const RefPtr& src) noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Gio::File]’ used but never defined
   inline ~RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:107:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr(const Glib::RefPtr<T_CppObject>&) [with T_CppObject = Gio::File]’ used but never defined
   inline RefPtr(const RefPtr& src) noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:95:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr() [with T_CppObject = Gio::DBus::InterfaceInfo]’ used but never defined
   inline RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Gio::DBus::InterfaceInfo]’ used but never defined
   inline ~RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:95:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr() [with T_CppObject = Gio::Cancellable]’ used but never defined
   inline RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Gio::Cancellable]’ used but never defined
   inline ~RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:95:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr() [with T_CppObject = Glib::MainContext]’ used but never defined
   inline RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Glib::MainContext]’ used but never defined
   inline ~RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Gio::Volume]’ used but never defined
/usr/include/glibmm-2.4/glibmm/refptr.h:107:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr(const Glib::RefPtr<T_CppObject>&) [with T_CppObject = Gio::Volume]’ used but never defined
   inline RefPtr(const RefPtr& src) noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Pango::LayoutLine]’ used but never defined
   inline ~RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:107:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr(const Glib::RefPtr<T_CppObject>&) [with T_CppObject = Pango::LayoutLine]’ used but never defined
   inline RefPtr(const RefPtr& src) noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Gtk::TreeModel]’ used but never defined
   inline ~RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:107:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr(const Glib::RefPtr<T_CppObject>&) [with T_CppObject = Gtk::TreeModel]’ used but never defined
   inline RefPtr(const RefPtr& src) noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:160:23: warning: inline function ‘T_CppObject\* Glib::RefPtr<T_CppObject>::operator->() const [with T_CppObject = Gtk::Printer]’ used but never defined
   inline T_CppObject\* operator->() const noexcept;
                       ^
/usr/include/glibmm-2.4/glibmm/refptr.h:95:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr() [with T_CppObject = Gtk::ListStore]’ used but never defined
   inline RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Gtk::ListStore]’ used but never defined
   inline ~RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:160:23: warning: inline function ‘T_CppObject\* Glib::RefPtr<T_CppObject>::operator->() const [with T_CppObject = Gtk::ListStore]’ used but never defined
   inline T_CppObject\* operator->() const noexcept;
                       ^
/usr/include/glibmm-2.4/glibmm/refptr.h:170:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::operator bool() const [with T_CppObject = Gio::File]’ used but never defined
   inline operator bool() const noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:160:23: warning: inline function ‘T_CppObject\* Glib::RefPtr<T_CppObject>::operator->() const [with T_CppObject = Gio::File]’ used but never defined
   inline T_CppObject\* operator->() const noexcept;
                       ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Gio::FileOutputStream]’ used but never defined
   inline ~RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Gio::DataOutputStream]’ used but never defined
/usr/include/glibmm-2.4/glibmm/refptr.h:160:23: warning: inline function ‘T_CppObject\* Glib::RefPtr<T_CppObject>::operator->() const [with T_CppObject = Gio::DataOutputStream]’ used but never defined
   inline T_CppObject\* operator->() const noexcept;
                       ^
/usr/include/glibmm-2.4/glibmm/refptr.h:95:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::RefPtr() [with T_CppObject = Gtk::TreeSelection]’ used but never defined
   inline RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:98:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::~RefPtr() [with T_CppObject = Gtk::TreeSelection]’ used but never defined
   inline ~RefPtr() noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:160:23: warning: inline function ‘T_CppObject\* Glib::RefPtr<T_CppObject>::operator->() const [with T_CppObject = Gtk::TreeSelection]’ used but never defined
   inline T_CppObject\* operator->() const noexcept;
                       ^
/usr/include/glibmm-2.4/glibmm/refptr.h:160:23: warning: inline function ‘T_CppObject\* Glib::RefPtr<T_CppObject>::operator->() const [with T_CppObject = Glib::ByteArray]’ used but never defined
/usr/include/glibmm-2.4/glibmm/refptr.h:170:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::operator bool() const [with T_CppObject = Glib::ByteArray]’ used but never defined
   inline operator bool() const noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:160:23: warning: inline function ‘T_CppObject\* Glib::RefPtr<T_CppObject>::operator->() const [with T_CppObject = Gio::Mount]’ used but never defined
   inline T_CppObject\* operator->() const noexcept;
                       ^
/usr/include/glibmm-2.4/glibmm/refptr.h:170:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::operator bool() const [with T_CppObject = Gio::Mount]’ used but never defined
   inline operator bool() const noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:160:23: warning: inline function ‘T_CppObject\* Glib::RefPtr<T_CppObject>::operator->() const [with T_CppObject = Gio::Drive]’ used but never defined
   inline T_CppObject\* operator->() const noexcept;
                       ^
/usr/include/glibmm-2.4/glibmm/refptr.h:170:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::operator bool() const [with T_CppObject = Gio::Drive]’ used but never defined
   inline operator bool() const noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:160:23: warning: inline function ‘T_CppObject\* Glib::RefPtr<T_CppObject>::operator->() const [with T_CppObject = Gio::Volume]’ used but never defined
   inline T_CppObject\* operator->() const noexcept;
                       ^
/usr/include/glibmm-2.4/glibmm/refptr.h:170:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::operator bool() const [with T_CppObject = Gio::Volume]’ used but never defined
   inline operator bool() const noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:160:23: warning: inline function ‘T_CppObject\* Glib::RefPtr<T_CppObject>::operator->() const [with T_CppObject = Pango::LayoutLine]’ used but never defined
   inline T_CppObject\* operator->() const noexcept;
                       ^
/usr/include/glibmm-2.4/glibmm/refptr.h:170:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::operator bool() const [with T_CppObject = Pango::LayoutLine]’ used but never defined
   inline operator bool() const noexcept;
          ^
/usr/include/glibmm-2.4/glibmm/refptr.h:170:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::operator bool() const [with T_CppObject = Gtk::TreeModel]’ used but never defined
/usr/include/glibmm-2.4/glibmm/refptr.h:160:23: warning: inline function ‘T_CppObject\* Glib::RefPtr<T_CppObject>::operator->() const [with T_CppObject = Gtk::TreeModel]’ used but never defined
   inline T_CppObject\* operator->() const noexcept;
                       ^
/usr/include/glibmm-2.4/glibmm/refptr.h:160:23: warning: inline function ‘T_CppObject\* Glib::RefPtr<T_CppObject>::operator->() const [with T_CppObject = Gtk::RecentInfo]’ used but never defined
/usr/include/glibmm-2.4/glibmm/refptr.h:170:10: warning: inline function ‘Glib::RefPtr<T_CppObject>::operator bool() const [with T_CppObject = Gtk::RecentInfo]’ used but never defined
   inline operator bool() const noexcept;
          ^
Makefile:74: recipe for target 'jalv.select' failed
make: **\* [jalv.select] Error 1

**Comment by brummer10** [comment]
Hi funkmuscle
This should be GCC 5 related. I've just push a fix to git, please do a new pull and try again.
Let me know if it fixed the issue.

regards
hermann

**Comment by funkmuscle** [comment]
buddy it's working.. Thanx a Lot.

**Comment by brummer10** [comment]
Great, so I close this issue.
