### ISSUE TITLE
Support for a user-made blacklist

### ISSUE THREAD

**Issue by trebmuh** [brummer10/jalv_select#32]
Some plugins are not able to be opened/launched by jalv, hence neither jalv.select. See https://github.com/Yoshimi/yoshimi/issues/42 for an example.

Then as a user, I'd like to have the possibility to blacklist such plugin and the not having them to show up anymore in the jalv.select list (until I un-blacklist them).

**Comment by SpotlightKid** [comment]
I can not speak for the brummer10, but I like the idea. Would you need a facility in the GUI to blacklist plugins or would, say, listing them in a file be good enough? How about un-blacklisting?

Another idea would be to allow patterns in the blacklist, to e.g. hide all plugins from a certain maker by setting the root URI of this maker as a pattern. Example:

    http://example.com/plugins#[-a-z]+$

This would blacklist `http://example.com/plugins#foo` as well as `http://example.com/plugins#ding-dong`.

**Comment by trebmuh** [comment]
> Would you need a facility in the GUI to blacklist plugins or would, say, listing them in a file be good enough? How about un-blacklisting?

Having a GUI facility to blacklist/unblacklist them would be great from a non-techy POV. I'm thinking here of a facility along the line of the Favorite plugins one.

**Comment by SpotlightKid** [comment]
If the point of blacklisting plugins is to hide them from the GUI, how would you make them visible again to un-blacklist a plugin?

**Comment by trebmuh** [comment]
Like with the "Favorite" list, ie: a case-box to be ticked.

**Comment by brummer10** [comment]
In general it would be easy to implement, just, I ain't like to blow the GUI up with more options. 
Maybe we could rework the "Fav" button, make it a select box, to select between "All", "Favourites", and additional "Blacklist", were you could tick plugins to un/blacklist them?

**Comment by trebmuh** [comment]
Sounds good @brummer10

**Comment by trebmuh** [comment]
Just pinging here as a reminder, no rush.

**Comment by brummer10** [comment]
Hi
Thanks for the reminder, so I've pushed support for blacklist plugins now to git. 

regards
hermann

**Comment by trebmuh** [comment]
Thanks @brummer10 , it's awesome!

If I get it correctly, the blacklisted plugins are now put in .config/jalv.select.back .
I'd like to request something if possible. I'd like to be able as packager/admin to pre-setup a list of such blacklisted plugins. I know that rncbc allows putting such a file into /etc/xdg/rncbc.org/xxxx.conf .

Then, when launched, the logic could be "If no .config/jalv.select.back is found, then copy /etc/xdg/brummer/jalv.select.back into a new ~/.config/jalv.select.back file and use this new file. If .config/jalv.select.back is found, then use it".

I'd recommend and like jalv.select.conf to be the same too.

What your thought about this?

**Comment by SpotlightKid** [comment]
Relevant standard:

https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html

**Comment by brummer10** [comment]
Currently, the config files use  `Glib::get_user_config_dir ( )` which returns `$XDG_CONFIG_HOME`.
When no config file found, the read function simply return. Surly I could add a second check, to read from a other location, when no file found in default path, to allow package installed config files.

**Comment by brummer10** [comment]
And done, you could put config files into `/etc/xdg/jalvselect` now. 
They will be used (and copied) only when no user config file is found.

**Comment by trebmuh** [comment]
Hi @brummer10 

I might be doing a mistake since it doesn't seems to be working here.

I've got this:
```
$ cat /etc/xdg/jalvselect/jalv.select.back 
http://yoshimi.sourceforge.net/lv2_plugin
http://yoshimi.sourceforge.net/lv2_plugin_multi
```
So, both Yoshimi should be blacklisted.

When I'm starting jalv.select (with the `~/.config/jalv.select.back` file erased beforeward), they aren't blacklisted and, when I'm closing jalv.select, a `~/.config/jalv.select.back` file is created, but empty.

Can you see an obvious mistake I'm doing here? Or might that be a bug I found?

**Comment by brummer10** [comment]
Yes, a bug. I've fixed it now with the above commit. 

regards
hermann

**Comment by trebmuh** [comment]
And now, it works as a charm. Thanks @brummer10 !
