### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by trebmuh** [brummer10/jalv_select#33]
Hi @brummer10 
I was wondering if you could have a release (1.1 maybe) in order to start having a localisable jalv_select as an official release?

**Comment by brummer10** [comment]
Hi

Sorry, it have to wait. 
I've a hard-disk-failure (click of death) and lost all my work, because my last backup it to long ago. 

Now I've to set up a new machine and re-create my work, before I could handle requests like that. 

regards
hermann

**Comment by trebmuh** [comment]
I'm sorry that happened to you.
No worries at all, we'll wait then.

Happy recovering!

**Comment by brummer10** [comment]
Okay, done, release v1.1 is out.

**Comment by trebmuh** [comment]
Thanks @brummer10 !
Closing here now.
