### ISSUE TITLE
colors clashing can clash with user theming

### ISSUE THREAD

**Issue by trebmuh** [brummer10/jalv_select#34]
From [the code](https://github.com/brummer10/jalv_select/blob/master/jalv.select.cpp#L350), it looks like the colors used by jalv_select are hard-coded. With regards to the theme used by the user, it can clash in a not well suited mix of theme-colors and jalv_select colors choice.

Would that be a good suggestion for jalv_select to pick up the colors from the theme rather than hard-coding these?

**Comment by brummer10** [comment]
Yes, it's a good suggestion and I've committed a fix. Using @base_color and shade now should reflect users theming.

**Comment by trebmuh** [comment]
Nice. Tested, it looks to work as expected.
Thanks @brummer10 :+1:
