### ISSUE TITLE
Shouldn't install files directly into share/

### ISSUE THREAD

**Issue by yurivict** [brummer10/jalv_select#35]
The version 1.1 installs the file share/jalv.select.mo.
Normally, data files should go into ```share/{pkg-name}/```.

**Comment by yurivict** [comment]
I could change it in the Makefile, but the path should correspond to the path where it will be read, and I don't know what this path is.

**Comment by brummer10** [comment]
Hi Yuri

I don't know how localisation is handled on BSDs, but on Linux the usual place to put localisation files, in opposite to plain application data files,  is, and I guess it will be the same on BSDs.
/usr/share/locale/$(lang)/LC_MESSAGES/

so jalv.select localisation files go to:

/usr/share/locale/de_DE/LC_MESSAGES/jalv.select.mo
/usr/share/locale/fr_FR/LC_MESSAGES/jalv.select.mo

which is the path were gettext expect them.

**Comment by yurivict** [comment]
Sorry, I didn't describe the problem accurately the first time.

It installs the file as ```/usr/local/share/jalv-select/jalv.select.mo```.
It doesn't correspond to the above pattern.

The complete list of installed files:
```
bin/jalv.select
man/man1/jalv.select.1.gz
man/man1/jalv.select.fr.1.gz
share/applications/jalv.select.desktop
share/jalv-select/jalv.select.mo
share/pixmaps/lv2.png
share/pixmaps/lv2_16.png
```

**Comment by brummer10** [comment]
Yea, that's bad. 
Do you know a way for BSD to install files including there path? To replace --parents

**Comment by yurivict** [comment]
The only way I know is to do ```mkdir -p {path}```.

**Comment by brummer10** [comment]
Okay, I'll investigate.

**Comment by brummer10** [comment]
Hi Yuri

So I've found a way to do it without using --parent, could you please try if it work for you and let me know if the issues been solved?

regards
hermann

**Comment by yurivict** [comment]
Yes, both issues are gone, thank you.
Are you going to make another release?

**Comment by brummer10** [comment]
Yes, done v1.2 is out.

regards
hermann
