### ISSUE TITLE
Debian build fail

### ISSUE THREAD

**Issue by RattusSolarus** [brummer10/jalv_select#38]
The instructions for Debian build don't work due to lack of a debian directory or control file. I did manage to build it with make/make install.
jalv and jalv_select seem to be functioning correctly now. Thanks for your work! I'm trying it to load room correction EQ in JACK rather than in the monitor stage of Mixbus. pajackconnect also is quite nice. I'm borrowing ideas from AVL to use on Debian Buster with KDE.

**Comment by brummer10** [comment]
Hi
Works here. 
Running `make deb` will create the debian folder including the control file and build the package.
You need to have `dh_make` installed to create the debian folder and `dpkg-dev` and `fakeroot` to build the package.
The debian package will be created one folder above the source folder.

**Comment by RattusSolarus** [comment]
I'm so embarrassed, teach me to do unfamiliar things during graveyard hours after a long day.
Thank you so much for replying. All good now.

**Comment by brummer10** [comment]
You are welcome.
