### ISSUE TITLE
Search with translated plugins

### ISSUE THREAD

**Issue by trebmuh** [brummer10/jalv_select#39]
Using the "searching" box (middle bottom) to search for a plugin. Let's take a plugin which have a French translation: noise-repellent (which is translated with "Répulseur de bruit" in French). If I'm searching for its French name, all good, I find it. But if I'm searching for its English name, jalv.select doesn't find it.

I assume here that is because jalv.select is launched with a FR locale, then it searches for the FR name of the LV2 plugins. This make sense.

I suggest here to extend the search for it to be be performed in FR and EN. Then, it'll find any of the FR or EN name of an LV2 plugin. An easy use-case is: I find an awesome-page about the XXXX even-more-awesome-plugin, with XXXX being its EN name. Then I try to find it with its English name in the search box, but I only know its English name. -> can't find it.

**Comment by brummer10** [comment]
The ttl files been read by lilv, and lilv do the filtering for the locale settings, this is regardless of the app using it support translation or not.
Lilv has a option to disable LANG filtering, but that seems to be unstable. 
The API sad that lilv will return all entry's when filtering is disabled, but it return the one or the other, were you never know witch one it is next call. 
Using this will make the search function more or less a Gambling.
In a case like you mention, best results will be reached by search for the category of the plug.

regards
hermann

**Comment by brummer10** [comment]
@trebmuh  Please. never ever again ping me on anything related to @drobilla. As any communication with him ends up in a disaster. I've better way's to spend my time.

**Comment by drobilla** [comment]
Blocked due to this unbelievably inappropriate behaviour.

Should anyone wish to address this issue, the necessary information is available in the linked issue.

**Comment by brummer10** [comment]
@drodilla 
As I said, I've better things to to, so claim down and go your way. Have a nice day.
regards
hermann

**Comment by drobilla** [comment]
Yeah, _I'm_ the one who needs to calm down here :joy:

**Comment by brummer10** [comment]
@drobilla
In fact, you are the one who don't understand the issue, but claim you are. So, conversation is useless, isn't it? As I said, I've better things to do as explain it to you (as you are shown that you've no interest in solving it). So please, have a nice day, do what ever you find useful, but stop to go on my nerve. I'm done with it and hope you are to.

**Comment by brummer10** [comment]
@trebmuh 
I've implemented a button which allow you now to switch to English (only for the LV2 interface) and as well back to the native system language. Hope that solve the issue.
Forgot to mention that this button will only appear when the system language isn't English.
