### ISSUE TITLE
license

### ISSUE THREAD

**Issue by trebmuh** [brummer10/jalv_select#5]
Hi Herman,
First of all, thanks for this really useful little tool.

I've not been able to find any mention about license in the source. Can you please add a LICENSE.TXT or something ?

Cheers

**Comment by brummer10** [comment]
Hi
I'm glade you find it usefull.
It's Puplic Domain, I'll add it to the source file as soon I could.

regards
Hermann

**Comment by trebmuh** [comment]
Thanks.

**Comment by brummer10** [comment]
Hi

So I've solved the issue by adding the un-license notice in the source. Thanks for pointing out the issue, I'll close it now.

regards
hermann

**Comment by trebmuh** [comment]
Sweat :+1:
